// Generated by CoffeeScript 1.10.0
(function() {
    var api, assert, database, supertest, test;

    database = require('../lib/database');

    api = require('../lib/api');

    supertest = require('supertest');

    assert = require('assert');

    test = supertest(api);

    describe('GifTV API', function() {
        return describe('Categories', function() {
            beforeEach(function() {
                return database.drop().then(function() {
                    return database.sync();
                });
            });
            return it('works', function(done) {
                return test.get('/v1/trending').expect(200).end(done);
            });
        });
    });

}).call(this);
