// Generated by CoffeeScript 1.10.0
(function() {
  var Router, app;

  Router = require('express').Router;

  app = new Router();

  app.use('/trending', require('./trending'));

  module.exports = app;

}).call(this);
