// Generated by CoffeeScript 1.10.0
(function() {
  var Promise, Router, app, database, getQuery, giphyRequest, request, spotifyRequest;

  Router = require('express').Router;

  Promise = require('bluebird');

  database = require('../database');

  request = require('request-promise');

  app = new Router();

  giphyRequest = {
    uri: 'http://api.giphy.com/v1/gifs/trending',
    qs: {
      api_key: 'dc6zaTOxFJmzC',
      limit: 3
    },
    json: true
  };

  spotifyRequest = function(query) {
    return {
      uri: 'https://api.spotify.com/v1/search',
      qs: {
        type: 'track',
        limit: 1,
        offset: 0,
        q: query
      },
      json: true
    };
  };

  app.get('/', function(req, res, next) {
    return request(giphyRequest).then(function(gifs) {
      return gifs.data;
    }).map(function(gif) {
      return request(spotifyRequest(getQuery(gif.slug))).then(function(res) {
        var musicUrl, ref;
        if (musicUrl = (ref = res.tracks.items[0]) != null ? ref.preview_url : void 0) {
          return {
            gif: gif.images.original.mp4,
            music: musicUrl
          };
        } else {
          return null;
        }
      });
    }).filter(function(result) {
      return result;
    }).map(function(result) {
      database.models.gif.create(result);
      return result;
    }).then(function(result) {
      return res.send(result);
    });
  });

  getQuery = function(slug) {
    return slug.split('-')[0];
  };

  module.exports = app;

}).call(this);
