// Generated by CoffeeScript 1.10.0
(function() {
  var Router, app, async, getQuery, request;

  Router = require('express').Router;

  request = require('request');

  async = require('async');

  app = new Router();

  app.get('/', function(req, res, next) {
    return request('http://api.giphy.com/v1/gifs/trending?api_key=dc6zaTOxFJmzC&limit=3', {
      json: true
    }, function(error, response, body) {
      return async.map(body.data, function(gif, done) {
        return request("https://api.spotify.com/v1/search?type=track&limit=1&offset=0&q=" + (getQuery(gif.slug)), {
          json: true
        }, function(error, response, body) {
          var musicUrl, ref;
          if (musicUrl = (ref = body.tracks.items[0]) != null ? ref.preview_url : void 0) {
            return done(null, {
              gif: gif.images.original.mp4,
              music: musicUrl
            });
          } else {
            return done(null, null);
          }
        });
      }, function(err, result) {
        return res.send(result.filter(function(item) {
          return item;
        }));
      });
    });
  });

  getQuery = function(slug) {
    return slug.split('-')[0];
  };

  module.exports = app;

}).call(this);
