// Generated by CoffeeScript 1.10.0
(function() {
  var Router, app, request;

  Router = require('express').Router;

  request = require('request');

  app = new Router();

  app.get('/', function(req, res, next) {
    return request('http://api.giphy.com/v1/gifs/trending?api_key=dc6zaTOxFJmzC', function(error, response, body) {
      return res.send(body);
    });
  });

  module.exports = app;

}).call(this);
