// Generated by CoffeeScript 1.10.0
(function() {
    var Sequelize;

    Sequelize = require('sequelize');

    module.exports = function(database) {
        var GifWithMusic;
        return GifWithMusic = database.define('gif_with_music', {
            gif: Sequelize.STRING
        });
    };

}).call(this);
