// Generated by CoffeeScript 1.10.0
(function() {
  var Sequelize;

  Sequelize = require('sequelize');

  module.exports = function(database) {
    var category, gif;
    gif = database.define('gif', {
      gif: Sequelize.STRING,
      music: Sequelize.STRING
    });
    category = database.define('category', {
      name: Sequelize.STRING
    });
    return gif.belongsTo(category);
  };

}).call(this);
