// Generated by CoffeeScript 1.10.0
(function() {
    var BackgroundManager;

    BackgroundManager = (function() {
        function BackgroundManager() {
        }

        return BackgroundManager;

    })();

    module.exports = BackgroundManager();

}).call(this);
