// Generated by CoffeeScript 1.10.0
(function() {
  var Sequelize, sequelize;

  Sequelize = require('sequelize');

  sequelize = new Sequelize('test', null, null, {
    dialect: 'sqlite'
  });

  require('./model/v1')(sequelize);

  module.exports = sequelize;

}).call(this);
