// Generated by CoffeeScript 1.10.0
(function() {
    var Sequelize, sequelize;

    Sequelize = require('sequelize');

    sequelize = new Sequelize(process.env.DATABASE_URL || 'sqlite://memory');

    require('./model/v1')(sequelize);

    module.exports = sequelize;

}).call(this);
